#!/usr/bin/env sh

git checkout master
npm run build; surge -d cocotte-app.com -p dist

git checkout enceinte-manger.com
git merge master
npm run build; surge -d enceinte-manger.com -p dist

git checkout enceinte-alimentation.com
git merge master
npm run build; surge -d enceinte-alimentation.com -p dist

git checkout alimentation-enceinte.com
git merge master
npm run build; surge -d alimentation-enceinte.com -p dist
